// Generated by CoffeeScript 1.3.3

jQuery(function() {
  var dd, render, xs;
  dd = function() {
    $("#drag-item").draggable({
      helper: "clone"
    });
    return $(".rim").droppable({
      tolerance: "touch",
      over: function(e, ui) {
        var $dragged_div, $dropped_th;
        $dropped_th = $(this);
        $dragged_div = ui.draggable;
        return $dropped_th.text($dropped_th.text()).animate({
          width: 100
        }, 100);
      },
      out: function() {
        return $(this).text("").animate({
          width: 10
        }, 100);
      },
      drop: function(e, ui) {
        var n, text;
        text = ui.draggable.text();
        n = $(this).attr("n");
        xs.splice(n, 0, text);
        return render();
      }
    });
  };
  xs = ["hoge", "fuga", "piyo"];
  render = function() {
    var table;
    table = $("<table/>").attr("id", "t");
    _(3).times(function() {
      var $tr;
      $tr = $("<tr/>");
      $tr.append($("<td/>").addClass("rim").attr("n", 0));
      _(xs).each(function(x, n) {
        $tr.append($("<td/>").text(x));
        return $tr.append($("<td/>").addClass("rim").attr("n", n + 1));
      });
      return table.append($tr);
    });
    $("#t").replaceWith(table);
    return dd();
  };
  return render();
});
